// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type {
  GetEntityDefinitionsData,
  GetEntityDefinitionsResponses,
  GetEntityDefinitionsErrors,
  CreateEntityDefinitionData,
  CreateEntityDefinitionResponses,
  CreateEntityDefinitionErrors,
  DeleteEntityDefinitionData,
  DeleteEntityDefinitionResponses,
  DeleteEntityDefinitionErrors,
  CreateEntityData,
  CreateEntityResponses,
  CreateEntityErrors,
  DeleteEntityData,
  DeleteEntityResponses,
  DeleteEntityErrors,
  GetEntityData,
  GetEntityResponses,
  GetEntityErrors,
  GetEntitiesData,
  GetEntitiesResponses,
  GetEntitiesErrors,
  DeleteEntityRelationData,
  DeleteEntityRelationResponses,
  DeleteEntityRelationErrors,
  CreateEntityRelationData,
  CreateEntityRelationResponses,
  CreateEntityRelationErrors,
  CreateChatTitleData,
  CreateChatTitleResponses,
  CreateChatTitleErrors,
  GetChatsData,
  GetChatsResponses,
  GetChatsErrors,
  CreateChatData,
  CreateChatResponses,
  CreateChatErrors,
  DeleteChatData,
  DeleteChatResponses,
  DeleteChatErrors,
  GetChatData,
  GetChatResponses,
  GetChatErrors,
  UpdateChatData,
  UpdateChatResponses,
  UpdateChatErrors,
  GetChatMessagesData,
  GetChatMessagesResponses,
  GetChatMessagesErrors,
  PostChatMessagesData,
  PostChatMessagesResponses,
  PostChatMessagesErrors,
  PostClerkWebhookData,
  PostClerkWebhookResponses,
  PostClerkWebhookErrors,
  PostStripeWebhookData,
  PostStripeWebhookResponses,
  PostStripeWebhookErrors,
  GetEnvironmentsData,
  GetEnvironmentsResponses,
  GetEnvironmentsErrors,
  CreateEnvironmentData,
  CreateEnvironmentResponses,
  CreateEnvironmentErrors,
  GetEnvironmentStatusData,
  GetEnvironmentStatusResponses,
  GetEnvironmentStatusErrors,
  GetSubscriptionsData,
  GetSubscriptionsResponses,
  GetSubscriptionsErrors,
  GetTokensData,
  GetTokensResponses,
  GetTokensErrors,
  CreateTokenData,
  CreateTokenResponses,
  CreateTokenErrors,
  ListEnvironmentUsersData,
  ListEnvironmentUsersResponses,
  ListEnvironmentUsersErrors,
  CreateEnvironmentUserData,
  CreateEnvironmentUserResponses,
  CreateEnvironmentUserErrors,
  DeleteEnvironmentUserData,
  DeleteEnvironmentUserResponses,
  DeleteEnvironmentUserErrors,
  GetEnvironmentUserData,
  GetEnvironmentUserResponses,
  GetEnvironmentUserErrors,
  UpdateEnvironmentUserData,
  UpdateEnvironmentUserResponses,
  UpdateEnvironmentUserErrors,
  InviteEnvironmentUserData,
  InviteEnvironmentUserResponses,
  InviteEnvironmentUserErrors,
  BulkInviteEnvironmentUsersData,
  BulkInviteEnvironmentUsersResponses,
  BulkInviteEnvironmentUsersErrors,
  GetModelprovidersData,
  GetModelprovidersResponses,
  GetModelprovidersErrors,
  CreateModelproviderData,
  CreateModelproviderResponses,
  CreateModelproviderErrors,
  DeleteModelproviderData,
  DeleteModelproviderResponses,
  DeleteModelproviderErrors,
  GetModelproviderData,
  GetModelproviderResponses,
  GetModelproviderErrors,
  GetMcpendpointsData,
  GetMcpendpointsResponses,
  GetMcpendpointsErrors,
  CreateMcpendpointData,
  CreateMcpendpointResponses,
  CreateMcpendpointErrors,
  DeleteMcpendpointData,
  DeleteMcpendpointResponses,
  DeleteMcpendpointErrors,
  GetMcpendpointData,
  GetMcpendpointResponses,
  GetMcpendpointErrors,
  UpdateMcpendpointData,
  UpdateMcpendpointResponses,
  UpdateMcpendpointErrors,
  GetModelsData,
  GetModelsResponses,
  GetModelsErrors,
  CreateModelData,
  CreateModelResponses,
  CreateModelErrors,
  DeleteModelData,
  DeleteModelResponses,
  DeleteModelErrors,
  GetModelData,
  GetModelResponses,
  GetModelErrors,
  ListOauthServicesData,
  ListOauthServicesResponses,
  ListOauthServicesErrors,
  CreateOauthServiceData,
  CreateOauthServiceResponses,
  CreateOauthServiceErrors,
  DeleteOauthServiceData,
  DeleteOauthServiceResponses,
  DeleteOauthServiceErrors,
  GetOauthServiceData,
  GetOauthServiceResponses,
  GetOauthServiceErrors,
  UpdateOauthServiceData,
  UpdateOauthServiceResponses,
  UpdateOauthServiceErrors,
  GetOauthAuthorizationUrlData,
  GetOauthAuthorizationUrlResponses,
  GetOauthAuthorizationUrlErrors,
  ExchangeOauthTokenData,
  ExchangeOauthTokenResponses,
  ExchangeOauthTokenErrors,
  ListOauthTokensData,
  ListOauthTokensResponses,
  ListOauthTokensErrors,
  RevokeOauthTokenData,
  RevokeOauthTokenResponses,
  RevokeOauthTokenErrors,
} from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Retrieve all entity definitions with their versions
 * Fetches a list of all entity definitions and their associated versions from the database. Requires 'list:entitydefinitions' permission.
 */
export const getEntityDefinitions = <ThrowOnError extends boolean = false>(
  options?: Options<GetEntityDefinitionsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetEntityDefinitionsResponses,
    GetEntityDefinitionsErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/entities/definitions',
    ...options,
  });
};

/**
 * Create Entity Definition
 */
export const createEntityDefinition = <ThrowOnError extends boolean = false>(
  options: Options<CreateEntityDefinitionData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateEntityDefinitionResponses,
    CreateEntityDefinitionErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/entities/definitions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Delete an entity definition
 * Deletes an entity definition and all its versions. Requires 'delete:entitydefinitions' permission.
 */
export const deleteEntityDefinition = <ThrowOnError extends boolean = false>(
  options: Options<DeleteEntityDefinitionData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteEntityDefinitionResponses,
    DeleteEntityDefinitionErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/entities/definitions/{definition_id}',
    ...options,
  });
};

/**
 * Create a resource based on an entity definition
 * Creates a new entity based on the specified group, version, namespace, and kind. Requires 'create:entities' permission.
 */
export const createEntity = <ThrowOnError extends boolean = false>(
  options: Options<CreateEntityData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateEntityResponses,
    CreateEntityErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/entities/{group}/{version}/namespace/{namespace}/{plural}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Delete a specific entity
 * Deletes a specific entity from the knowledge graph. Requires 'delete:entities' permission.
 */
export const deleteEntity = <ThrowOnError extends boolean = false>(
  options: Options<DeleteEntityData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteEntityResponses,
    DeleteEntityErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/entities/{group}/{version}/{kind}/{namespace}/{name}',
    ...options,
  });
};

/**
 * Retrieve a specific entity by name
 * Fetches a specific entity based on group, version, namespace, plural, and name. Requires 'read:entities' permission.
 */
export const getEntity = <ThrowOnError extends boolean = false>(
  options: Options<GetEntityData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<GetEntityResponses, GetEntityErrors, ThrowOnError>({
    url: '/api/v1/entities/{group}/{version}/{kind}/{namespace}/{name}',
    ...options,
  });
};

/**
 * Query entities with optional field selectors
 * Retrieves entities from the knowledge graph, optionally filtered by field selectors. Field selectors use dot notation for nested properties (e.g., 'spec.metadata.owner=team-a'). Requires 'read:entities' permission.
 */
export const getEntities = <ThrowOnError extends boolean = false>(
  options?: Options<GetEntitiesData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetEntitiesResponses,
    GetEntitiesErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/entities/',
    ...options,
  });
};

/**
 * Delete a relation between entities
 * Deletes a specific relation between two entities. Requires 'delete:entityrelations' permission.
 */
export const deleteEntityRelation = <ThrowOnError extends boolean = false>(
  options: Options<DeleteEntityRelationData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteEntityRelationResponses,
    DeleteEntityRelationErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/entities/relations',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Create Entity Relation
 */
export const createEntityRelation = <ThrowOnError extends boolean = false>(
  options: Options<CreateEntityRelationData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateEntityRelationResponses,
    CreateEntityRelationErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/entities/relations',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Post Chat Title
 * Generate a title for a chat based on the first message.
 */
export const createChatTitle = <ThrowOnError extends boolean = false>(
  options: Options<CreateChatTitleData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateChatTitleResponses,
    CreateChatTitleErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/chat/title',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Get Chats
 */
export const getChats = <ThrowOnError extends boolean = false>(
  options?: Options<GetChatsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<GetChatsResponses, GetChatsErrors, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/chat/',
    ...options,
  });
};

/**
 * Create Chat
 */
export const createChat = <ThrowOnError extends boolean = false>(
  options: Options<CreateChatData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateChatResponses,
    CreateChatErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/chat/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Delete Chat
 */
export const deleteChat = <ThrowOnError extends boolean = false>(
  options: Options<DeleteChatData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteChatResponses,
    DeleteChatErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/chat/{chat_id}',
    ...options,
  });
};

/**
 * Get Chat
 */
export const getChat = <ThrowOnError extends boolean = false>(
  options: Options<GetChatData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<GetChatResponses, GetChatErrors, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/chat/{chat_id}',
    ...options,
  });
};

/**
 * Update Chat
 */
export const updateChat = <ThrowOnError extends boolean = false>(
  options: Options<UpdateChatData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<UpdateChatResponses, UpdateChatErrors, ThrowOnError>(
    {
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/api/v1/chat/{chat_id}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    }
  );
};

/**
 * Get Chat Messages
 */
export const getChatMessages = <ThrowOnError extends boolean = false>(
  options: Options<GetChatMessagesData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetChatMessagesResponses,
    GetChatMessagesErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/chat/{chat_id}/messages',
    ...options,
  });
};

/**
 * Post Chat Messages
 */
export const postChatMessages = <ThrowOnError extends boolean = false>(
  options: Options<PostChatMessagesData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    PostChatMessagesResponses,
    PostChatMessagesErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/chat/{chat_id}/messages',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Post Clerk Webhook
 */
export const postClerkWebhook = <ThrowOnError extends boolean = false>(
  options: Options<PostClerkWebhookData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    PostClerkWebhookResponses,
    PostClerkWebhookErrors,
    ThrowOnError
  >({
    url: '/system/api/v1/webhooks/clerk',
    ...options,
  });
};

/**
 * Post Stripe Webhook
 */
export const postStripeWebhook = <ThrowOnError extends boolean = false>(
  options: Options<PostStripeWebhookData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    PostStripeWebhookResponses,
    PostStripeWebhookErrors,
    ThrowOnError
  >({
    url: '/system/api/v1/webhooks/stripe',
    ...options,
  });
};

/**
 * Get Environments
 */
export const getEnvironments = <ThrowOnError extends boolean = false>(
  options?: Options<GetEnvironmentsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetEnvironmentsResponses,
    GetEnvironmentsErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/environments',
    ...options,
  });
};

/**
 * Create Environment
 */
export const createEnvironment = <ThrowOnError extends boolean = false>(
  options: Options<CreateEnvironmentData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateEnvironmentResponses,
    CreateEnvironmentErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/environments',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Get Environment Status
 */
export const getEnvironmentStatus = <ThrowOnError extends boolean = false>(
  options: Options<GetEnvironmentStatusData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetEnvironmentStatusResponses,
    GetEnvironmentStatusErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/environments/{env_id}/status',
    ...options,
  });
};

/**
 * Get Subscriptions
 */
export const getSubscriptions = <ThrowOnError extends boolean = false>(
  options?: Options<GetSubscriptionsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetSubscriptionsResponses,
    GetSubscriptionsErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/subscriptions',
    ...options,
  });
};

/**
 * Get Tokens
 * Get all API tokens for the authenticated user.
 */
export const getTokens = <ThrowOnError extends boolean = false>(
  options?: Options<GetTokensData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<GetTokensResponses, GetTokensErrors, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/tokens',
    ...options,
  });
};

/**
 * Create Token
 */
export const createToken = <ThrowOnError extends boolean = false>(
  options: Options<CreateTokenData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateTokenResponses,
    CreateTokenErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/tokens',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * List Environment Users
 * List all users in an environment (organization members).
 */
export const listEnvironmentUsers = <ThrowOnError extends boolean = false>(
  options: Options<ListEnvironmentUsersData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    ListEnvironmentUsersResponses,
    ListEnvironmentUsersErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/environments/{environment_id}/users',
    ...options,
  });
};

/**
 * Create Environment User
 * Create a new environment user by adding them to the Clerk organization.
 */
export const createEnvironmentUser = <ThrowOnError extends boolean = false>(
  options: Options<CreateEnvironmentUserData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateEnvironmentUserResponses,
    CreateEnvironmentUserErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/environments/{environment_id}/users',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Delete Environment User
 * Remove a user from an environment (organization).
 */
export const deleteEnvironmentUser = <ThrowOnError extends boolean = false>(
  options: Options<DeleteEnvironmentUserData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteEnvironmentUserResponses,
    DeleteEnvironmentUserErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/environments/{environment_id}/users/{user_id}',
    ...options,
  });
};

/**
 * Get Environment User
 * Get a specific environment user.
 */
export const getEnvironmentUser = <ThrowOnError extends boolean = false>(
  options: Options<GetEnvironmentUserData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetEnvironmentUserResponses,
    GetEnvironmentUserErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/environments/{environment_id}/users/{user_id}',
    ...options,
  });
};

/**
 * Update Environment User
 * Update an environment user's role.
 */
export const updateEnvironmentUser = <ThrowOnError extends boolean = false>(
  options: Options<UpdateEnvironmentUserData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<
    UpdateEnvironmentUserResponses,
    UpdateEnvironmentUserErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/environments/{environment_id}/users/{user_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Invite Environment User
 * Invite a user to an environment (organization).
 */
export const inviteEnvironmentUser = <ThrowOnError extends boolean = false>(
  options: Options<InviteEnvironmentUserData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    InviteEnvironmentUserResponses,
    InviteEnvironmentUserErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/environments/{environment_id}/users/invite',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Bulk Invite Environment Users
 * Bulk invite multiple users to an environment (organization).
 */
export const bulkInviteEnvironmentUsers = <ThrowOnError extends boolean = false>(
  options: Options<BulkInviteEnvironmentUsersData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    BulkInviteEnvironmentUsersResponses,
    BulkInviteEnvironmentUsersErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/environments/{environment_id}/users/bulk-invite',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Get Modelproviders
 * List all Model Provider configurations for the authenticated user and environment.
 */
export const getModelproviders = <ThrowOnError extends boolean = false>(
  options?: Options<GetModelprovidersData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetModelprovidersResponses,
    GetModelprovidersErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/modelproviders',
    ...options,
  });
};

/**
 * Create Modelprovider
 * Create a new Model Provider configuration.
 */
export const createModelprovider = <ThrowOnError extends boolean = false>(
  options: Options<CreateModelproviderData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateModelproviderResponses,
    CreateModelproviderErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/modelproviders',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Delete Modelprovider
 * Delete a specific Model Provider configuration by ID.
 */
export const deleteModelprovider = <ThrowOnError extends boolean = false>(
  options: Options<DeleteModelproviderData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteModelproviderResponses,
    DeleteModelproviderErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/modelproviders/{provider_id}',
    ...options,
  });
};

/**
 * Get Modelprovider
 * Get a specific Model Provider configuration by ID.
 */
export const getModelprovider = <ThrowOnError extends boolean = false>(
  options: Options<GetModelproviderData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetModelproviderResponses,
    GetModelproviderErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/modelproviders/{provider_id}',
    ...options,
  });
};

/**
 * Get Mcpendpoints
 * List all MCP Endpoint configurations for the authenticated user and environment.
 */
export const getMcpendpoints = <ThrowOnError extends boolean = false>(
  options?: Options<GetMcpendpointsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetMcpendpointsResponses,
    GetMcpendpointsErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/mcpendpoints',
    ...options,
  });
};

/**
 * Create Mcpendpoint
 * Create a new MCP Endpoint configuration.
 */
export const createMcpendpoint = <ThrowOnError extends boolean = false>(
  options: Options<CreateMcpendpointData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateMcpendpointResponses,
    CreateMcpendpointErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/mcpendpoints',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Delete Mcpendpoint
 * Delete a specific MCP Endpoint configuration by ID.
 */
export const deleteMcpendpoint = <ThrowOnError extends boolean = false>(
  options: Options<DeleteMcpendpointData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteMcpendpointResponses,
    DeleteMcpendpointErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/mcpendpoints/{mcpendpoint_id}',
    ...options,
  });
};

/**
 * Get Mcpendpoint
 * Get a specific MCP Endpoint configuration by ID.
 */
export const getMcpendpoint = <ThrowOnError extends boolean = false>(
  options: Options<GetMcpendpointData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetMcpendpointResponses,
    GetMcpendpointErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/mcpendpoints/{mcpendpoint_id}',
    ...options,
  });
};

/**
 * Update Mcpendpoint
 * Update a specific MCP Endpoint configuration by ID.
 */
export const updateMcpendpoint = <ThrowOnError extends boolean = false>(
  options: Options<UpdateMcpendpointData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<
    UpdateMcpendpointResponses,
    UpdateMcpendpointErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/mcpendpoints/{mcpendpoint_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Get Models
 * List all model configurations for the authenticated user and environment.
 */
export const getModels = <ThrowOnError extends boolean = false>(
  options?: Options<GetModelsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<GetModelsResponses, GetModelsErrors, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/models',
    ...options,
  });
};

/**
 * Create Model
 * Create a new model configuration.
 */
export const createModel = <ThrowOnError extends boolean = false>(
  options: Options<CreateModelData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateModelResponses,
    CreateModelErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/models',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Delete Model
 * Delete a specific model configuration by name.
 */
export const deleteModel = <ThrowOnError extends boolean = false>(
  options: Options<DeleteModelData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteModelResponses,
    DeleteModelErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/models/{model_name}',
    ...options,
  });
};

/**
 * Get Model
 * Get a specific model configuration by name.
 */
export const getModel = <ThrowOnError extends boolean = false>(
  options: Options<GetModelData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<GetModelResponses, GetModelErrors, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/models/{model_name}',
    ...options,
  });
};

/**
 * List Oauth Services
 */
export const listOauthServices = <ThrowOnError extends boolean = false>(
  options?: Options<ListOauthServicesData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListOauthServicesResponses,
    ListOauthServicesErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/oauth/services',
    ...options,
  });
};

/**
 * Create Oauth Service
 */
export const createOauthService = <ThrowOnError extends boolean = false>(
  options: Options<CreateOauthServiceData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateOauthServiceResponses,
    CreateOauthServiceErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/oauth/services',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Delete Oauth Service
 */
export const deleteOauthService = <ThrowOnError extends boolean = false>(
  options: Options<DeleteOauthServiceData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteOauthServiceResponses,
    DeleteOauthServiceErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/oauth/services/{service_id}',
    ...options,
  });
};

/**
 * Get Oauth Service
 */
export const getOauthService = <ThrowOnError extends boolean = false>(
  options: Options<GetOauthServiceData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetOauthServiceResponses,
    GetOauthServiceErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/oauth/services/{service_id}',
    ...options,
  });
};

/**
 * Update Oauth Service
 */
export const updateOauthService = <ThrowOnError extends boolean = false>(
  options: Options<UpdateOauthServiceData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<
    UpdateOauthServiceResponses,
    UpdateOauthServiceErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/oauth/services/{service_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Get Authorization Url
 */
export const getOauthAuthorizationUrl = <ThrowOnError extends boolean = false>(
  options: Options<GetOauthAuthorizationUrlData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    GetOauthAuthorizationUrlResponses,
    GetOauthAuthorizationUrlErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/oauth/authorize',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Exchange Code For Token
 */
export const exchangeOauthToken = <ThrowOnError extends boolean = false>(
  options: Options<ExchangeOauthTokenData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    ExchangeOauthTokenResponses,
    ExchangeOauthTokenErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/oauth/token',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * List User Tokens
 */
export const listOauthTokens = <ThrowOnError extends boolean = false>(
  options?: Options<ListOauthTokensData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListOauthTokensResponses,
    ListOauthTokensErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/oauth/tokens',
    ...options,
  });
};

/**
 * Revoke Token
 */
export const revokeOauthToken = <ThrowOnError extends boolean = false>(
  options: Options<RevokeOauthTokenData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    RevokeOauthTokenResponses,
    RevokeOauthTokenErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/oauth/tokens/{service_name}',
    ...options,
  });
};
