// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type {
  GetHealthHealthzGetData,
  GetHealthHealthzGetResponses,
  GetEnvironmentsData,
  GetEnvironmentsResponses,
  GetEnvironmentsErrors,
  CreateEnvironmentData,
  CreateEnvironmentResponses,
  CreateEnvironmentErrors,
  GetEnvironmentStatusData,
  GetEnvironmentStatusResponses,
  GetEnvironmentStatusErrors,
  GetSubscriptionsData,
  GetSubscriptionsResponses,
  GetSubscriptionsErrors,
  GetTokensSystemApiV1TokensGetData,
  GetTokensSystemApiV1TokensGetResponses,
  GetTokensSystemApiV1TokensGetErrors,
  CreateTokenData,
  CreateTokenResponses,
  CreateTokenErrors,
  GetModelprovidersData,
  GetModelprovidersResponses,
  GetModelprovidersErrors,
  CreateModelproviderData,
  CreateModelproviderResponses,
  CreateModelproviderErrors,
  DeleteModelproviderData,
  DeleteModelproviderResponses,
  DeleteModelproviderErrors,
  GetModelproviderData,
  GetModelproviderResponses,
  GetModelproviderErrors,
  GetMcpendpointsData,
  GetMcpendpointsResponses,
  GetMcpendpointsErrors,
  CreateMcpendpointData,
  CreateMcpendpointResponses,
  CreateMcpendpointErrors,
  DeleteMcpendpointData,
  DeleteMcpendpointResponses,
  DeleteMcpendpointErrors,
  GetMcpendpointData,
  GetMcpendpointResponses,
  GetMcpendpointErrors,
  GetModelsData,
  GetModelsResponses,
  GetModelsErrors,
  CreateModelData,
  CreateModelResponses,
  CreateModelErrors,
  DeleteModelData,
  DeleteModelResponses,
  DeleteModelErrors,
  GetModelData,
  GetModelResponses,
  GetModelErrors,
  GetEntityDefinitionsData,
  GetEntityDefinitionsResponses,
  GetEntityDefinitionsErrors,
  CreateEntityDefinitionData,
  CreateEntityDefinitionResponses,
  CreateEntityDefinitionErrors,
  CreateEntityData,
  CreateEntityResponses,
  CreateEntityErrors,
  GetEntityData,
  GetEntityResponses,
  GetEntityErrors,
  GetEntitiesData,
  GetEntitiesResponses,
  GetEntitiesErrors,
  CreateEntityRelationData,
  CreateEntityRelationResponses,
  CreateEntityRelationErrors,
  CreateChatTitleData,
  CreateChatTitleResponses,
  CreateChatTitleErrors,
  GetChatsData,
  GetChatsResponses,
  GetChatsErrors,
  CreateChatData,
  CreateChatResponses,
  CreateChatErrors,
  DeleteChatData,
  DeleteChatResponses,
  DeleteChatErrors,
  GetChatData,
  GetChatResponses,
  GetChatErrors,
  UpdateChatData,
  UpdateChatResponses,
  UpdateChatErrors,
  GetChatMessagesData,
  GetChatMessagesResponses,
  GetChatMessagesErrors,
  PostChatMessagesData,
  PostChatMessagesResponses,
  PostChatMessagesErrors,
  PostClerkWebhookData,
  PostClerkWebhookResponses,
  PostClerkWebhookErrors,
  PostStripeWebhookData,
  PostStripeWebhookResponses,
  PostStripeWebhookErrors,
} from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Perform a Health Check
 */
export const getHealthHealthzGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetHealthHealthzGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetHealthHealthzGetResponses,
    unknown,
    ThrowOnError
  >({
    url: '/healthz',
    ...options,
  });
};

/**
 * Get Environments
 */
export const getEnvironments = <ThrowOnError extends boolean = false>(
  options?: Options<GetEnvironmentsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetEnvironmentsResponses,
    GetEnvironmentsErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/environments',
    ...options,
  });
};

/**
 * Create Environment
 */
export const createEnvironment = <ThrowOnError extends boolean = false>(
  options: Options<CreateEnvironmentData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateEnvironmentResponses,
    CreateEnvironmentErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/environments',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Get Environment Status
 */
export const getEnvironmentStatus = <ThrowOnError extends boolean = false>(
  options: Options<GetEnvironmentStatusData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetEnvironmentStatusResponses,
    GetEnvironmentStatusErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/environments/{env_id}/status',
    ...options,
  });
};

/**
 * Get Subscriptions
 */
export const getSubscriptions = <ThrowOnError extends boolean = false>(
  options?: Options<GetSubscriptionsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetSubscriptionsResponses,
    GetSubscriptionsErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/subscriptions',
    ...options,
  });
};

/**
 * Get Tokens
 * Get all API tokens for the authenticated user.
 */
export const getTokensSystemApiV1TokensGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetTokensSystemApiV1TokensGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetTokensSystemApiV1TokensGetResponses,
    GetTokensSystemApiV1TokensGetErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/tokens',
    ...options,
  });
};

/**
 * Create Token
 */
export const createToken = <ThrowOnError extends boolean = false>(
  options: Options<CreateTokenData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateTokenResponses,
    CreateTokenErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/tokens',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Get Modelproviders
 * List all Model Provider configurations for the authenticated user and environment.
 */
export const getModelproviders = <ThrowOnError extends boolean = false>(
  options?: Options<GetModelprovidersData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetModelprovidersResponses,
    GetModelprovidersErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/modelproviders',
    ...options,
  });
};

/**
 * Create Modelprovider
 * Create a new Model Provider configuration.
 */
export const createModelprovider = <ThrowOnError extends boolean = false>(
  options: Options<CreateModelproviderData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateModelproviderResponses,
    CreateModelproviderErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/modelproviders',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Delete Modelprovider
 * Delete a specific Model Provider configuration by ID.
 */
export const deleteModelprovider = <ThrowOnError extends boolean = false>(
  options: Options<DeleteModelproviderData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteModelproviderResponses,
    DeleteModelproviderErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/modelproviders/{provider_id}',
    ...options,
  });
};

/**
 * Get Modelprovider
 * Get a specific Model Provider configuration by ID.
 */
export const getModelprovider = <ThrowOnError extends boolean = false>(
  options: Options<GetModelproviderData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetModelproviderResponses,
    GetModelproviderErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/modelproviders/{provider_id}',
    ...options,
  });
};

/**
 * Get Mcpendpoints
 * List all MCP Endpoint configurations for the authenticated user and environment.
 */
export const getMcpendpoints = <ThrowOnError extends boolean = false>(
  options?: Options<GetMcpendpointsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetMcpendpointsResponses,
    GetMcpendpointsErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/mcpendpoints',
    ...options,
  });
};

/**
 * Create Mcpendpoint
 * Create a new MCP Endpoint configuration.
 */
export const createMcpendpoint = <ThrowOnError extends boolean = false>(
  options: Options<CreateMcpendpointData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateMcpendpointResponses,
    CreateMcpendpointErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/mcpendpoints',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Delete Mcpendpoint
 * Delete a specific MCP Endpoint configuration by ID.
 */
export const deleteMcpendpoint = <ThrowOnError extends boolean = false>(
  options: Options<DeleteMcpendpointData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteMcpendpointResponses,
    DeleteMcpendpointErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/mcpendpoints/{mcpendpoint_id}',
    ...options,
  });
};

/**
 * Get Mcpendpoint
 * Get a specific MCP Endpoint configuration by ID.
 */
export const getMcpendpoint = <ThrowOnError extends boolean = false>(
  options: Options<GetMcpendpointData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetMcpendpointResponses,
    GetMcpendpointErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/mcpendpoints/{mcpendpoint_id}',
    ...options,
  });
};

/**
 * Get Models
 * List all model configurations for the authenticated user and environment.
 */
export const getModels = <ThrowOnError extends boolean = false>(
  options?: Options<GetModelsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<GetModelsResponses, GetModelsErrors, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/models',
    ...options,
  });
};

/**
 * Create Model
 * Create a new model configuration.
 */
export const createModel = <ThrowOnError extends boolean = false>(
  options: Options<CreateModelData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateModelResponses,
    CreateModelErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/models',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Delete Model
 * Delete a specific model configuration by name.
 */
export const deleteModel = <ThrowOnError extends boolean = false>(
  options: Options<DeleteModelData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteModelResponses,
    DeleteModelErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/models/{model_name}',
    ...options,
  });
};

/**
 * Get Model
 * Get a specific model configuration by name.
 */
export const getModel = <ThrowOnError extends boolean = false>(
  options: Options<GetModelData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<GetModelResponses, GetModelErrors, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/system/api/v1/models/{model_name}',
    ...options,
  });
};

/**
 * Retrieve all entity definitions with their versions
 * Fetches a list of all entity definitions and their associated versions from the database. Requires 'list:entitydefinitions' permission.
 */
export const getEntityDefinitions = <ThrowOnError extends boolean = false>(
  options?: Options<GetEntityDefinitionsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetEntityDefinitionsResponses,
    GetEntityDefinitionsErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/entities/definitions',
    ...options,
  });
};

/**
 * Create Entity Definition
 */
export const createEntityDefinition = <ThrowOnError extends boolean = false>(
  options: Options<CreateEntityDefinitionData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateEntityDefinitionResponses,
    CreateEntityDefinitionErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/entities/definitions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Create a resource based on an entity definition
 * Creates a new entity based on the specified group, version, namespace, and kind. Requires 'create:entities' permission.
 */
export const createEntity = <ThrowOnError extends boolean = false>(
  options: Options<CreateEntityData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateEntityResponses,
    CreateEntityErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/entities/{group}/{version}/namespace/{namespace}/{plural}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Retrieve a specific entity by name
 * Fetches a specific entity based on group, version, namespace, plural, and name. Requires 'read:entities' permission.
 */
export const getEntity = <ThrowOnError extends boolean = false>(
  options: Options<GetEntityData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<GetEntityResponses, GetEntityErrors, ThrowOnError>({
    url: '/api/v1/entities/{group}/{version}/{kind}/{namespace}/{name}',
    ...options,
  });
};

/**
 * Get Entities
 */
export const getEntities = <ThrowOnError extends boolean = false>(
  options?: Options<GetEntitiesData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetEntitiesResponses,
    GetEntitiesErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/entities/',
    ...options,
  });
};

/**
 * Create Entity Relation
 */
export const createEntityRelation = <ThrowOnError extends boolean = false>(
  options: Options<CreateEntityRelationData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateEntityRelationResponses,
    CreateEntityRelationErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/entities/relations',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Post Chat Title
 */
export const createChatTitle = <ThrowOnError extends boolean = false>(
  options: Options<CreateChatTitleData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateChatTitleResponses,
    CreateChatTitleErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/chat/title',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Get Chats
 */
export const getChats = <ThrowOnError extends boolean = false>(
  options?: Options<GetChatsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<GetChatsResponses, GetChatsErrors, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/chat/',
    ...options,
  });
};

/**
 * Create Chat
 */
export const createChat = <ThrowOnError extends boolean = false>(
  options: Options<CreateChatData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateChatResponses,
    CreateChatErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/chat/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Delete Chat
 */
export const deleteChat = <ThrowOnError extends boolean = false>(
  options: Options<DeleteChatData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteChatResponses,
    DeleteChatErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/chat/{chat_id}',
    ...options,
  });
};

/**
 * Get Chat
 */
export const getChat = <ThrowOnError extends boolean = false>(
  options: Options<GetChatData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<GetChatResponses, GetChatErrors, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/chat/{chat_id}',
    ...options,
  });
};

/**
 * Update Chat
 */
export const updateChat = <ThrowOnError extends boolean = false>(
  options: Options<UpdateChatData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<UpdateChatResponses, UpdateChatErrors, ThrowOnError>(
    {
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/api/v1/chat/{chat_id}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    }
  );
};

/**
 * Get Chat Messages
 */
export const getChatMessages = <ThrowOnError extends boolean = false>(
  options: Options<GetChatMessagesData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetChatMessagesResponses,
    GetChatMessagesErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/chat/{chat_id}/messages',
    ...options,
  });
};

/**
 * Post Chat Messages
 */
export const postChatMessages = <ThrowOnError extends boolean = false>(
  options: Options<PostChatMessagesData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    PostChatMessagesResponses,
    PostChatMessagesErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/chat/{chat_id}/messages',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Post Clerk Webhook
 */
export const postClerkWebhook = <ThrowOnError extends boolean = false>(
  options: Options<PostClerkWebhookData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    PostClerkWebhookResponses,
    PostClerkWebhookErrors,
    ThrowOnError
  >({
    url: '/system/api/v1/webhooks/clerk',
    ...options,
  });
};

/**
 * Post Stripe Webhook
 */
export const postStripeWebhook = <ThrowOnError extends boolean = false>(
  options: Options<PostStripeWebhookData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    PostStripeWebhookResponses,
    PostStripeWebhookErrors,
    ThrowOnError
  >({
    url: '/system/api/v1/webhooks/stripe',
    ...options,
  });
};
