// This file is auto-generated by @hey-api/openapi-ts

/**
 * ApiTokenCreate
 */
export type ApiTokenCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Expires At
   */
  expires_at?: string | null;
  /**
   * Scopes
   */
  scopes?: Array<string>;
};

/**
 * ApiTokenResponse
 */
export type ApiTokenResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * User Id
   */
  user_id: string;
  /**
   * Expires At
   */
  expires_at?: string | null;
  /**
   * Token
   */
  token: string;
  /**
   * Scopes
   */
  scopes?: Array<string> | null;
  /**
   * Active
   */
  active?: boolean;
};

/**
 * ChatMessageCreate
 */
export type ChatMessageCreate = {
  /**
   * Role
   */
  role: string;
  /**
   * Content
   */
  content: string | Array<TypedChatMessageContent>;
};

/**
 * ChatMessageRouter
 */
export type ChatMessageRouter = {
  /**
   * Id
   */
  id: string;
  /**
   * Chatid
   */
  chatId: string;
  /**
   * Role
   */
  role: string;
  /**
   * Content
   */
  content: string | Array<TypedChatMessageContent>;
  /**
   * Createdat
   */
  createdAt: string;
};

/**
 * ChatSession
 */
export type ChatSession = {
  /**
   * Id
   */
  id: string;
  /**
   * Userid
   */
  userId: string;
  /**
   * Title
   */
  title: string;
  visibility?: ChatVisibility;
  /**
   * Createdat
   */
  createdAt?: string;
};

/**
 * ChatSessionCreate
 */
export type ChatSessionCreate = {
  /**
   * Id
   */
  id?: string | null;
  /**
   * Userid
   */
  userId: string;
  /**
   * Title
   */
  title: string;
  visibility?: ChatVisibility;
};

/**
 * ChatSessionUpdate
 */
export type ChatSessionUpdate = {
  visibility?: ChatVisibility;
};

/**
 * ChatTitleRequest
 */
export type ChatTitleRequest = {
  /**
   * Message
   */
  message: string;
};

/**
 * ChatTitleResponse
 */
export type ChatTitleResponse = {
  /**
   * Title
   */
  title: string;
};

/**
 * ChatVisibility
 */
export type ChatVisibility = 'public' | 'private';

/**
 * Entity
 */
export type Entity = {
  /**
   * Apiversion
   */
  apiVersion: string;
  /**
   * Kind
   */
  kind: string;
  metadata: EntityMetadata;
  /**
   * Spec
   */
  spec?: {
    [key: string]: unknown;
  };
};

/**
 * EntityDefinitionResponse
 */
export type EntityDefinitionResponse = {
  /**
   * Group
   */
  group: string;
  /**
   * Kind
   */
  kind: string;
  /**
   * List Kind
   */
  list_kind: string;
  /**
   * Plural
   */
  plural?: string | null;
  /**
   * Singular
   */
  singular: string;
  /**
   * Name
   */
  name?: string;
  /**
   * Spec
   */
  spec: {
    [key: string]: unknown;
  };
  /**
   * Storage
   */
  storage?: boolean;
  /**
   * Served
   */
  served?: boolean;
  /**
   * Id
   */
  id: string;
};

/**
 * EntityDefinitionSpec
 */
export type EntityDefinitionSpec = {
  /**
   * Group
   */
  group: string;
  /**
   * Kind
   */
  kind: string;
  /**
   * List Kind
   */
  list_kind: string;
  /**
   * Plural
   */
  plural?: string | null;
  /**
   * Singular
   */
  singular: string;
  /**
   * Name
   */
  name?: string;
  /**
   * Spec
   */
  spec: {
    [key: string]: unknown;
  };
  /**
   * Storage
   */
  storage?: boolean;
  /**
   * Served
   */
  served?: boolean;
};

/**
 * EntityMetadata
 */
export type EntityMetadata = {
  /**
   * Name
   */
  name: string;
  /**
   * Namespace
   */
  namespace: string;
  /**
   * Labels
   */
  labels?: {
    [key: string]: string;
  };
  /**
   * Annotations
   */
  annotations?: {
    [key: string]: string;
  };
};

/**
 * EntityReference
 */
export type EntityReference = {
  /**
   * Apiversion
   */
  apiVersion: string;
  /**
   * Kind
   */
  kind: string;
  /**
   * Name
   */
  name: string;
  /**
   * Namespace
   */
  namespace?: string;
};

/**
 * EntityReferenceResponse
 */
export type EntityReferenceResponse = {
  /**
   * Apiversion
   */
  apiVersion: string;
  /**
   * Kind
   */
  kind: string;
  /**
   * Name
   */
  name: string;
  /**
   * Namespace
   */
  namespace?: string;
  /**
   * Id
   * Return a unique identifier for the entity.
   */
  readonly id: string;
};

/**
 * EntityRelation
 */
export type EntityRelation = {
  /**
   * Namespace
   */
  namespace?: string;
  /**
   * Relation
   */
  relation: string;
  source: EntityReference;
  target: EntityReference;
};

/**
 * EntityRelationResponse
 */
export type EntityRelationResponse = {
  /**
   * Namespace
   */
  namespace?: string;
  /**
   * Relation
   */
  relation: string;
  source: EntityReferenceResponse;
  target: EntityReferenceResponse;
};

/**
 * EntityResponse
 */
export type EntityResponse = {
  /**
   * Apiversion
   */
  apiVersion: string;
  /**
   * Kind
   */
  kind: string;
  metadata: EntityMetadata;
  /**
   * Spec
   */
  spec?: {
    [key: string]: unknown;
  };
  /**
   * Id
   * Return a unique identifier for the entity.
   */
  readonly id: string;
  /**
   * Plural
   * Return the plural form of the kind.
   */
  readonly plural: string;
  /**
   * Group
   * Return the group part of the apiVersion.
   */
  readonly group: string;
  /**
   * Version
   * Return the version part of the apiVersion.
   */
  readonly version: string;
  /**
   * Name
   * Return the name of the resource.
   */
  readonly name: string;
  /**
   * Namespace
   * Return the namespace of the resource.
   */
  readonly namespace: string;
};

/**
 * EntityResultSetResponse
 */
export type EntityResultSetResponse = {
  /**
   * Primary Entities
   */
  primary_entities?: Array<EntityResponse>;
  /**
   * Related Entities
   */
  related_entities?: Array<EntityResponse>;
  /**
   * Relations
   */
  relations?: Array<EntityRelationResponse>;
};

/**
 * EnvironmentCreate
 */
export type EnvironmentCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Invited Users
   */
  invited_users?: Array<string>;
  /**
   * Stripe Subscription Id
   */
  stripe_subscription_id: string;
  /**
   * Instance Url
   */
  instance_url: string;
};

/**
 * EnvironmentResponse
 */
export type EnvironmentResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Slug
   */
  slug: string;
  /**
   * Clerk Organization Id
   */
  clerk_organization_id: string;
  /**
   * Customer Id
   */
  customer_id: string;
  /**
   * Subscription Id
   */
  subscription_id: string;
};

/**
 * EnvironmentUserBulkInvite
 */
export type EnvironmentUserBulkInvite = {
  /**
   * Invitations
   */
  invitations: Array<EnvironmentUserInvite>;
};

/**
 * EnvironmentUserCreate
 */
export type EnvironmentUserCreate = {
  /**
   * Email Address
   */
  email_address: string;
  /**
   * Role
   */
  role?: 'member' | 'admin';
};

/**
 * EnvironmentUserInvite
 */
export type EnvironmentUserInvite = {
  /**
   * Email Address
   */
  email_address: string;
  /**
   * Role
   */
  role?: 'member' | 'admin';
};

/**
 * EnvironmentUserResponse
 */
export type EnvironmentUserResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Email Address
   */
  email_address: string;
  /**
   * Role
   */
  role: string;
  /**
   * Status
   */
  status: string;
  /**
   * Created At
   */
  created_at: number;
  /**
   * Updated At
   */
  updated_at: number;
};

/**
 * EnvironmentUserUpdate
 */
export type EnvironmentUserUpdate = {
  /**
   * Role
   */
  role: 'member' | 'admin';
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * MCPEndpointCreate
 */
export type McpEndpointCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Url
   */
  url: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Headers
   */
  headers?: {
    [key: string]: string;
  };
  /**
   * Devgraph Auth
   */
  devgraph_auth?: boolean;
  /**
   * Supports Resources
   */
  supports_resources?: boolean;
  /**
   * Oauth Service Id
   */
  oauth_service_id?: string | null;
  /**
   * Immutable
   */
  immutable?: boolean;
  /**
   * Active
   */
  active?: boolean;
};

/**
 * MCPEndpointResponse
 */
export type McpEndpointResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Url
   */
  url: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Headers
   */
  headers?: {
    [key: string]: string;
  };
  /**
   * Devgraph Auth
   */
  devgraph_auth?: boolean;
  /**
   * Supports Resources
   */
  supports_resources?: boolean;
  /**
   * Oauth Service Id
   */
  oauth_service_id?: string | null;
  /**
   * Immutable
   */
  immutable?: boolean;
  /**
   * Active
   */
  active?: boolean;
};

/**
 * MCPEndpointUpdate
 */
export type McpEndpointUpdate = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Url
   */
  url?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Headers
   */
  headers?: {
    [key: string]: string;
  } | null;
  /**
   * Devgraph Auth
   */
  devgraph_auth?: boolean | null;
  /**
   * Supports Resources
   */
  supports_resources?: boolean | null;
  /**
   * Oauth Service Id
   */
  oauth_service_id?: string | null;
  /**
   * Immutable
   */
  immutable?: boolean | null;
  /**
   * Active
   */
  active?: boolean | null;
};

/**
 * ModelCreate
 */
export type ModelCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Provider Id
   */
  provider_id: string;
  /**
   * Default
   */
  default?: boolean;
};

/**
 * ModelProviderCreate
 */
export type ModelProviderCreate = {
  /**
   * Data
   */
  data:
    | ({
        type: 'openai';
      } & OpenAiModelProviderCreate)
    | ({
        type: 'xai';
      } & XaiModelProviderCreate);
};

/**
 * ModelProviderResponse
 */
export type ModelProviderResponse =
  | ({
      type: 'openai';
    } & OpenAiModelProviderResponse)
  | ({
      type: 'xai';
    } & XaiModelProviderResponse);

/**
 * ModelResponse
 */
export type ModelResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Provider Id
   */
  provider_id: string;
  /**
   * Default
   */
  default?: boolean;
};

/**
 * OAuthAuthorizationRequest
 */
export type OAuthAuthorizationRequest = {
  /**
   * Service Id
   */
  service_id: string;
  /**
   * Scopes
   */
  scopes?: Array<string> | null;
  /**
   * Redirect Uri
   */
  redirect_uri?: string | null;
  /**
   * State
   */
  state?: string | null;
};

/**
 * OAuthAuthorizationResponse
 */
export type OAuthAuthorizationResponse = {
  /**
   * Authorization Url
   */
  authorization_url: string;
  /**
   * State
   */
  state: string;
};

/**
 * OAuthServiceCreate
 */
export type OAuthServiceCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Display Name
   */
  display_name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Client Id
   */
  client_id: string;
  /**
   * Client Secret
   */
  client_secret: string;
  /**
   * Authorization Url
   */
  authorization_url: string;
  /**
   * Token Url
   */
  token_url: string;
  /**
   * Userinfo Url
   */
  userinfo_url?: string | null;
  /**
   * Default Scopes
   */
  default_scopes?: Array<string> | null;
  /**
   * Supported Grant Types
   */
  supported_grant_types?: Array<string>;
  /**
   * Is Active
   */
  is_active?: boolean;
  /**
   * Icon Url
   */
  icon_url?: string | null;
  /**
   * Homepage Url
   */
  homepage_url?: string | null;
  /**
   * Additional Params
   */
  additional_params?: {
    [key: string]: unknown;
  } | null;
};

/**
 * OAuthServiceListResponse
 */
export type OAuthServiceListResponse = {
  /**
   * Services
   */
  services: Array<OAuthServiceResponse>;
  /**
   * Total
   */
  total: number;
};

/**
 * OAuthServiceResponse
 */
export type OAuthServiceResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Display Name
   */
  display_name: string;
  /**
   * Description
   */
  description: string | null;
  /**
   * Authorization Url
   */
  authorization_url: string;
  /**
   * Token Url
   */
  token_url: string;
  /**
   * Userinfo Url
   */
  userinfo_url: string | null;
  /**
   * Default Scopes
   */
  default_scopes: Array<string>;
  /**
   * Supported Grant Types
   */
  supported_grant_types: Array<string>;
  /**
   * Is Active
   */
  is_active: boolean;
  /**
   * Icon Url
   */
  icon_url: string | null;
  /**
   * Homepage Url
   */
  homepage_url: string | null;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
};

/**
 * OAuthServiceUpdate
 */
export type OAuthServiceUpdate = {
  /**
   * Display Name
   */
  display_name?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Client Id
   */
  client_id?: string | null;
  /**
   * Client Secret
   */
  client_secret?: string | null;
  /**
   * Authorization Url
   */
  authorization_url?: string | null;
  /**
   * Token Url
   */
  token_url?: string | null;
  /**
   * Userinfo Url
   */
  userinfo_url?: string | null;
  /**
   * Default Scopes
   */
  default_scopes?: Array<string> | null;
  /**
   * Supported Grant Types
   */
  supported_grant_types?: Array<string> | null;
  /**
   * Is Active
   */
  is_active?: boolean | null;
  /**
   * Icon Url
   */
  icon_url?: string | null;
  /**
   * Homepage Url
   */
  homepage_url?: string | null;
  /**
   * Additional Params
   */
  additional_params?: {
    [key: string]: unknown;
  } | null;
};

/**
 * OAuthTokenExchange
 */
export type OAuthTokenExchange = {
  /**
   * Service Id
   */
  service_id: string;
  /**
   * Code
   */
  code: string;
  /**
   * State
   */
  state?: string | null;
  /**
   * Redirect Uri
   */
  redirect_uri?: string | null;
};

/**
 * OAuthTokenResponse
 */
export type OAuthTokenResponse = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Token Type
   */
  token_type: string;
  /**
   * Expires In
   */
  expires_in?: number | null;
  /**
   * Refresh Token
   */
  refresh_token?: string | null;
  /**
   * Scopes
   */
  scopes: Array<string>;
};

/**
 * OpenAIModelProviderCreate
 */
export type OpenAiModelProviderCreate = {
  /**
   * Type
   */
  type: 'openai';
  /**
   * Name
   */
  name: string;
  /**
   * Api Key
   */
  api_key: string;
  /**
   * Default
   */
  default?: boolean;
};

/**
 * OpenAIModelProviderResponse
 */
export type OpenAiModelProviderResponse = {
  /**
   * Type
   */
  type: 'openai';
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Api Key
   */
  api_key: string;
  /**
   * Default
   */
  default?: boolean;
};

/**
 * PendingInvitationResponse
 */
export type PendingInvitationResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Email Address
   */
  email_address: string;
  /**
   * Role
   */
  role: string;
  /**
   * Status
   */
  status: string;
  /**
   * Created At
   */
  created_at: number;
  /**
   * Updated At
   */
  updated_at: number;
  /**
   * Expires At
   */
  expires_at?: number | null;
};

/**
 * PromptCreate
 */
export type PromptCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Content
   */
  content: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Active
   */
  active?: boolean;
  /**
   * Is Default
   */
  is_default?: boolean;
};

/**
 * PromptResponse
 */
export type PromptResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Content
   */
  content: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Active
   */
  active?: boolean;
  /**
   * Is Default
   */
  is_default?: boolean;
  /**
   * Environment Id
   */
  environment_id: string;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
};

/**
 * PromptUpdate
 */
export type PromptUpdate = {
  /**
   * Content
   */
  content?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Active
   */
  active?: boolean | null;
  /**
   * Is Default
   */
  is_default?: boolean | null;
};

/**
 * SubscriptionResponse
 */
export type SubscriptionResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Stripe Subscription Id
   */
  stripe_subscription_id: string;
  /**
   * Environment Id
   */
  environment_id: string;
  /**
   * Status
   */
  status: string;
  /**
   * Price Id
   */
  price_id: string;
  /**
   * Current Period Start
   */
  current_period_start: number;
  /**
   * Current Period End
   */
  current_period_end: number;
};

/**
 * TypedChatMessageContent
 */
export type TypedChatMessageContent = {
  /**
   * Type
   */
  type: string;
  /**
   * Text
   */
  text: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

/**
 * WebhookResponse
 */
export type WebhookResponse = {
  /**
   * Status
   */
  status: string;
};

/**
 * XAIModelProviderCreate
 */
export type XaiModelProviderCreate = {
  /**
   * Type
   */
  type: 'xai';
  /**
   * Name
   */
  name: string;
  /**
   * Api Key
   */
  api_key: string;
  /**
   * Default
   */
  default?: boolean;
};

/**
 * XAIModelProviderResponse
 */
export type XaiModelProviderResponse = {
  /**
   * Type
   */
  type: 'xai';
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Api Key
   */
  api_key: string;
  /**
   * Default
   */
  default?: boolean;
};

export type GetEntityDefinitionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/entities/definitions';
};

export type GetEntityDefinitionsErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type GetEntityDefinitionsResponses = {
  /**
   * Response Get Entity Definitions
   * Successful Response
   */
  200: Array<EntityDefinitionResponse>;
};

export type GetEntityDefinitionsResponse =
  GetEntityDefinitionsResponses[keyof GetEntityDefinitionsResponses];

export type CreateEntityDefinitionData = {
  body: EntityDefinitionSpec;
  path?: never;
  query?: never;
  url: '/api/v1/entities/definitions';
};

export type CreateEntityDefinitionErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateEntityDefinitionError =
  CreateEntityDefinitionErrors[keyof CreateEntityDefinitionErrors];

export type CreateEntityDefinitionResponses = {
  /**
   * Successful Response
   */
  201: EntityDefinitionResponse;
};

export type CreateEntityDefinitionResponse =
  CreateEntityDefinitionResponses[keyof CreateEntityDefinitionResponses];

export type DeleteEntityDefinitionData = {
  body?: never;
  path: {
    /**
     * Definition Id
     */
    definition_id: string;
  };
  query?: never;
  url: '/api/v1/entities/definitions/{definition_id}';
};

export type DeleteEntityDefinitionErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteEntityDefinitionError =
  DeleteEntityDefinitionErrors[keyof DeleteEntityDefinitionErrors];

export type DeleteEntityDefinitionResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteEntityDefinitionResponse =
  DeleteEntityDefinitionResponses[keyof DeleteEntityDefinitionResponses];

export type CreateEntityData = {
  body: Entity;
  path: {
    /**
     * Group
     */
    group: string;
    /**
     * Version
     */
    version: string;
    /**
     * Namespace
     */
    namespace: string;
    /**
     * Plural
     */
    plural: string;
  };
  query?: never;
  url: '/api/v1/entities/{group}/{version}/namespace/{namespace}/{plural}';
};

export type CreateEntityErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateEntityError = CreateEntityErrors[keyof CreateEntityErrors];

export type CreateEntityResponses = {
  /**
   * Successful Response
   */
  201: EntityResponse;
};

export type CreateEntityResponse = CreateEntityResponses[keyof CreateEntityResponses];

export type DeleteEntityData = {
  body?: never;
  path: {
    /**
     * Group
     */
    group: string;
    /**
     * Version
     */
    version: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Namespace
     */
    namespace: string;
    /**
     * Name
     */
    name: string;
  };
  query?: never;
  url: '/api/v1/entities/{group}/{version}/{kind}/{namespace}/{name}';
};

export type DeleteEntityErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteEntityError = DeleteEntityErrors[keyof DeleteEntityErrors];

export type DeleteEntityResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteEntityResponse = DeleteEntityResponses[keyof DeleteEntityResponses];

export type GetEntityData = {
  body?: never;
  path: {
    /**
     * Group
     */
    group: string;
    /**
     * Version
     */
    version: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Namespace
     */
    namespace: string;
    /**
     * Name
     */
    name: string;
  };
  query?: never;
  url: '/api/v1/entities/{group}/{version}/{kind}/{namespace}/{name}';
};

export type GetEntityErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetEntityError = GetEntityErrors[keyof GetEntityErrors];

export type GetEntityResponses = {
  /**
   * Successful Response
   */
  200: EntityResponse;
};

export type GetEntityResponse = GetEntityResponses[keyof GetEntityResponses];

export type GetEntitiesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Name
     */
    name?: string;
    /**
     * Label
     */
    label?: string;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Offset
     */
    offset?: number;
    /**
     * Fieldselector
     * Comma-separated field selectors in format 'key=value', supports dot notation for nested properties
     */
    fieldSelector?: string;
  };
  url: '/api/v1/entities/';
};

export type GetEntitiesErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetEntitiesError = GetEntitiesErrors[keyof GetEntitiesErrors];

export type GetEntitiesResponses = {
  /**
   * Successful Response
   */
  200: EntityResultSetResponse;
};

export type GetEntitiesResponse = GetEntitiesResponses[keyof GetEntitiesResponses];

export type DeleteEntityRelationData = {
  body: EntityRelation;
  path?: never;
  query: {
    /**
     * Namespace
     */
    namespace: string;
  };
  url: '/api/v1/entities/relations';
};

export type DeleteEntityRelationErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteEntityRelationError =
  DeleteEntityRelationErrors[keyof DeleteEntityRelationErrors];

export type DeleteEntityRelationResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteEntityRelationResponse =
  DeleteEntityRelationResponses[keyof DeleteEntityRelationResponses];

export type CreateEntityRelationData = {
  body: EntityRelation;
  path?: never;
  query: {
    /**
     * Namespace
     */
    namespace: string;
  };
  url: '/api/v1/entities/relations';
};

export type CreateEntityRelationErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateEntityRelationError =
  CreateEntityRelationErrors[keyof CreateEntityRelationErrors];

export type CreateEntityRelationResponses = {
  /**
   * Successful Response
   */
  201: EntityRelationResponse;
};

export type CreateEntityRelationResponse =
  CreateEntityRelationResponses[keyof CreateEntityRelationResponses];

export type CreateChatTitleData = {
  body: ChatTitleRequest;
  path?: never;
  query?: never;
  url: '/api/v1/chat/title';
};

export type CreateChatTitleErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateChatTitleError = CreateChatTitleErrors[keyof CreateChatTitleErrors];

export type CreateChatTitleResponses = {
  /**
   * Successful Response
   */
  200: ChatTitleResponse;
};

export type CreateChatTitleResponse = CreateChatTitleResponses[keyof CreateChatTitleResponses];

export type GetChatsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Offset
     */
    offset?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: '/api/v1/chat/';
};

export type GetChatsErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetChatsError = GetChatsErrors[keyof GetChatsErrors];

export type GetChatsResponses = {
  /**
   * Response Get Chats
   * Successful Response
   */
  200: Array<ChatSession>;
};

export type GetChatsResponse = GetChatsResponses[keyof GetChatsResponses];

export type CreateChatData = {
  body: ChatSessionCreate;
  path?: never;
  query?: never;
  url: '/api/v1/chat/';
};

export type CreateChatErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateChatError = CreateChatErrors[keyof CreateChatErrors];

export type CreateChatResponses = {
  /**
   * Successful Response
   */
  201: ChatSession;
};

export type CreateChatResponse = CreateChatResponses[keyof CreateChatResponses];

export type DeleteChatData = {
  body?: never;
  path: {
    /**
     * Chat Id
     */
    chat_id: string;
  };
  query?: never;
  url: '/api/v1/chat/{chat_id}';
};

export type DeleteChatErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteChatError = DeleteChatErrors[keyof DeleteChatErrors];

export type DeleteChatResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteChatResponse = DeleteChatResponses[keyof DeleteChatResponses];

export type GetChatData = {
  body?: never;
  path: {
    /**
     * Chat Id
     */
    chat_id: string;
  };
  query?: never;
  url: '/api/v1/chat/{chat_id}';
};

export type GetChatErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetChatError = GetChatErrors[keyof GetChatErrors];

export type GetChatResponses = {
  /**
   * Successful Response
   */
  200: ChatSession;
};

export type GetChatResponse = GetChatResponses[keyof GetChatResponses];

export type UpdateChatData = {
  body: ChatSessionUpdate;
  path: {
    /**
     * Chat Id
     */
    chat_id: string;
  };
  query?: never;
  url: '/api/v1/chat/{chat_id}';
};

export type UpdateChatErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateChatError = UpdateChatErrors[keyof UpdateChatErrors];

export type UpdateChatResponses = {
  /**
   * Successful Response
   */
  200: ChatSession;
};

export type UpdateChatResponse = UpdateChatResponses[keyof UpdateChatResponses];

export type GetChatMessagesData = {
  body?: never;
  path: {
    /**
     * Chat Id
     */
    chat_id: string;
  };
  query?: {
    /**
     * Limit
     */
    limit?: number;
    /**
     * Offset
     */
    offset?: number;
  };
  url: '/api/v1/chat/{chat_id}/messages';
};

export type GetChatMessagesErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetChatMessagesError = GetChatMessagesErrors[keyof GetChatMessagesErrors];

export type GetChatMessagesResponses = {
  /**
   * Response Get Chat Messages
   * Successful Response
   */
  200: Array<ChatMessageRouter>;
};

export type GetChatMessagesResponse = GetChatMessagesResponses[keyof GetChatMessagesResponses];

export type PostChatMessagesData = {
  /**
   * Msgs
   */
  body: Array<ChatMessageCreate>;
  path: {
    /**
     * Chat Id
     */
    chat_id: string;
  };
  query?: never;
  url: '/api/v1/chat/{chat_id}/messages';
};

export type PostChatMessagesErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PostChatMessagesError = PostChatMessagesErrors[keyof PostChatMessagesErrors];

export type PostChatMessagesResponses = {
  /**
   * Response Post Chat Messages
   * Successful Response
   */
  201: Array<ChatMessageRouter>;
};

export type PostChatMessagesResponse = PostChatMessagesResponses[keyof PostChatMessagesResponses];

export type PostClerkWebhookData = {
  body?: never;
  headers: {
    /**
     * Svix-Id
     */
    'Svix-Id': string;
    /**
     * Svix-Timestamp
     */
    'Svix-Timestamp': string;
    /**
     * Svix-Signature
     */
    'Svix-Signature': string;
  };
  path?: never;
  query?: never;
  url: '/system/api/v1/webhooks/clerk';
};

export type PostClerkWebhookErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PostClerkWebhookError = PostClerkWebhookErrors[keyof PostClerkWebhookErrors];

export type PostClerkWebhookResponses = {
  /**
   * Successful Response
   */
  201: WebhookResponse;
};

export type PostClerkWebhookResponse = PostClerkWebhookResponses[keyof PostClerkWebhookResponses];

export type PostStripeWebhookData = {
  body?: never;
  headers: {
    /**
     * Stripe-Signature
     */
    'Stripe-Signature': string;
  };
  path?: never;
  query?: never;
  url: '/system/api/v1/webhooks/stripe';
};

export type PostStripeWebhookErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PostStripeWebhookError = PostStripeWebhookErrors[keyof PostStripeWebhookErrors];

export type PostStripeWebhookResponses = {
  /**
   * Successful Response
   */
  201: WebhookResponse;
};

export type PostStripeWebhookResponse =
  PostStripeWebhookResponses[keyof PostStripeWebhookResponses];

export type GetEnvironmentsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/system/api/v1/environments';
};

export type GetEnvironmentsErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type GetEnvironmentsResponses = {
  /**
   * Response Get Environments
   * Successful Response
   */
  200: Array<EnvironmentResponse>;
};

export type GetEnvironmentsResponse = GetEnvironmentsResponses[keyof GetEnvironmentsResponses];

export type CreateEnvironmentData = {
  body: EnvironmentCreate;
  path?: never;
  query?: never;
  url: '/system/api/v1/environments';
};

export type CreateEnvironmentErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateEnvironmentError = CreateEnvironmentErrors[keyof CreateEnvironmentErrors];

export type CreateEnvironmentResponses = {
  /**
   * Successful Response
   */
  201: EnvironmentResponse;
};

export type CreateEnvironmentResponse =
  CreateEnvironmentResponses[keyof CreateEnvironmentResponses];

export type GetEnvironmentStatusData = {
  body?: never;
  path: {
    /**
     * Env Id
     */
    env_id: string;
  };
  query?: never;
  url: '/system/api/v1/environments/{env_id}/status';
};

export type GetEnvironmentStatusErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetEnvironmentStatusError =
  GetEnvironmentStatusErrors[keyof GetEnvironmentStatusErrors];

export type GetEnvironmentStatusResponses = {
  /**
   * Response Get Environment Status
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type GetEnvironmentStatusResponse =
  GetEnvironmentStatusResponses[keyof GetEnvironmentStatusResponses];

export type GetSubscriptionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/system/api/v1/subscriptions';
};

export type GetSubscriptionsErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type GetSubscriptionsResponses = {
  /**
   * Response Get Subscriptions
   * Successful Response
   */
  200: Array<SubscriptionResponse>;
};

export type GetSubscriptionsResponse = GetSubscriptionsResponses[keyof GetSubscriptionsResponses];

export type GetTokensData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/system/api/v1/tokens';
};

export type GetTokensErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type GetTokensResponses = {
  /**
   * Response Get Tokens
   * Successful Response
   */
  200: Array<ApiTokenResponse>;
};

export type GetTokensResponse = GetTokensResponses[keyof GetTokensResponses];

export type CreateTokenData = {
  body: ApiTokenCreate;
  path?: never;
  query?: never;
  url: '/system/api/v1/tokens';
};

export type CreateTokenErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateTokenError = CreateTokenErrors[keyof CreateTokenErrors];

export type CreateTokenResponses = {
  /**
   * Successful Response
   */
  201: ApiTokenResponse;
};

export type CreateTokenResponse = CreateTokenResponses[keyof CreateTokenResponses];

export type ListEnvironmentUsersData = {
  body?: never;
  path: {
    /**
     * Environment Id
     */
    environment_id: string;
  };
  query?: never;
  url: '/system/api/v1/environments/{environment_id}/users';
};

export type ListEnvironmentUsersErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListEnvironmentUsersError =
  ListEnvironmentUsersErrors[keyof ListEnvironmentUsersErrors];

export type ListEnvironmentUsersResponses = {
  /**
   * Response List Environment Users
   * Successful Response
   */
  200: Array<EnvironmentUserResponse>;
};

export type ListEnvironmentUsersResponse =
  ListEnvironmentUsersResponses[keyof ListEnvironmentUsersResponses];

export type CreateEnvironmentUserData = {
  body: EnvironmentUserCreate;
  path: {
    /**
     * Environment Id
     */
    environment_id: string;
  };
  query?: never;
  url: '/system/api/v1/environments/{environment_id}/users';
};

export type CreateEnvironmentUserErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateEnvironmentUserError =
  CreateEnvironmentUserErrors[keyof CreateEnvironmentUserErrors];

export type CreateEnvironmentUserResponses = {
  /**
   * Successful Response
   */
  201: EnvironmentUserResponse;
};

export type CreateEnvironmentUserResponse =
  CreateEnvironmentUserResponses[keyof CreateEnvironmentUserResponses];

export type GetPendingInvitationsData = {
  body?: never;
  path: {
    /**
     * Environment Id
     */
    environment_id: string;
  };
  query?: never;
  url: '/system/api/v1/environments/{environment_id}/users/pending';
};

export type GetPendingInvitationsErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetPendingInvitationsError =
  GetPendingInvitationsErrors[keyof GetPendingInvitationsErrors];

export type GetPendingInvitationsResponses = {
  /**
   * Response Get Pending Invitations
   * Successful Response
   */
  200: Array<PendingInvitationResponse>;
};

export type GetPendingInvitationsResponse =
  GetPendingInvitationsResponses[keyof GetPendingInvitationsResponses];

export type DeleteEnvironmentUserData = {
  body?: never;
  path: {
    /**
     * Environment Id
     */
    environment_id: string;
    /**
     * User Id
     */
    user_id: string;
  };
  query?: never;
  url: '/system/api/v1/environments/{environment_id}/users/{user_id}';
};

export type DeleteEnvironmentUserErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteEnvironmentUserError =
  DeleteEnvironmentUserErrors[keyof DeleteEnvironmentUserErrors];

export type DeleteEnvironmentUserResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteEnvironmentUserResponse =
  DeleteEnvironmentUserResponses[keyof DeleteEnvironmentUserResponses];

export type GetEnvironmentUserData = {
  body?: never;
  path: {
    /**
     * Environment Id
     */
    environment_id: string;
    /**
     * User Id
     */
    user_id: string;
  };
  query?: never;
  url: '/system/api/v1/environments/{environment_id}/users/{user_id}';
};

export type GetEnvironmentUserErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetEnvironmentUserError = GetEnvironmentUserErrors[keyof GetEnvironmentUserErrors];

export type GetEnvironmentUserResponses = {
  /**
   * Successful Response
   */
  200: EnvironmentUserResponse;
};

export type GetEnvironmentUserResponse =
  GetEnvironmentUserResponses[keyof GetEnvironmentUserResponses];

export type UpdateEnvironmentUserData = {
  body: EnvironmentUserUpdate;
  path: {
    /**
     * Environment Id
     */
    environment_id: string;
    /**
     * User Id
     */
    user_id: string;
  };
  query?: never;
  url: '/system/api/v1/environments/{environment_id}/users/{user_id}';
};

export type UpdateEnvironmentUserErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateEnvironmentUserError =
  UpdateEnvironmentUserErrors[keyof UpdateEnvironmentUserErrors];

export type UpdateEnvironmentUserResponses = {
  /**
   * Successful Response
   */
  200: EnvironmentUserResponse;
};

export type UpdateEnvironmentUserResponse =
  UpdateEnvironmentUserResponses[keyof UpdateEnvironmentUserResponses];

export type InviteEnvironmentUserData = {
  body: EnvironmentUserInvite;
  path: {
    /**
     * Environment Id
     */
    environment_id: string;
  };
  query?: never;
  url: '/system/api/v1/environments/{environment_id}/users/invite';
};

export type InviteEnvironmentUserErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type InviteEnvironmentUserError =
  InviteEnvironmentUserErrors[keyof InviteEnvironmentUserErrors];

export type InviteEnvironmentUserResponses = {
  /**
   * Successful Response
   */
  201: EnvironmentUserResponse;
};

export type InviteEnvironmentUserResponse =
  InviteEnvironmentUserResponses[keyof InviteEnvironmentUserResponses];

export type BulkInviteEnvironmentUsersData = {
  body: EnvironmentUserBulkInvite;
  path: {
    /**
     * Environment Id
     */
    environment_id: string;
  };
  query?: never;
  url: '/system/api/v1/environments/{environment_id}/users/bulk-invite';
};

export type BulkInviteEnvironmentUsersErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type BulkInviteEnvironmentUsersError =
  BulkInviteEnvironmentUsersErrors[keyof BulkInviteEnvironmentUsersErrors];

export type BulkInviteEnvironmentUsersResponses = {
  /**
   * Response Bulk Invite Environment Users
   * Successful Response
   */
  201: Array<EnvironmentUserResponse>;
};

export type BulkInviteEnvironmentUsersResponse =
  BulkInviteEnvironmentUsersResponses[keyof BulkInviteEnvironmentUsersResponses];

export type GetModelprovidersData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/system/api/v1/modelproviders';
};

export type GetModelprovidersErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type GetModelprovidersResponses = {
  /**
   * Response Get Modelproviders
   * Successful Response
   */
  200: Array<ModelProviderResponse>;
};

export type GetModelprovidersResponse =
  GetModelprovidersResponses[keyof GetModelprovidersResponses];

export type CreateModelproviderData = {
  body: ModelProviderCreate;
  path?: never;
  query?: never;
  url: '/system/api/v1/modelproviders';
};

export type CreateModelproviderErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateModelproviderError = CreateModelproviderErrors[keyof CreateModelproviderErrors];

export type CreateModelproviderResponses = {
  /**
   * Successful Response
   */
  201: ModelProviderResponse;
};

export type CreateModelproviderResponse =
  CreateModelproviderResponses[keyof CreateModelproviderResponses];

export type DeleteModelproviderData = {
  body?: never;
  path: {
    /**
     * Provider Id
     */
    provider_id: string;
  };
  query?: never;
  url: '/system/api/v1/modelproviders/{provider_id}';
};

export type DeleteModelproviderErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteModelproviderError = DeleteModelproviderErrors[keyof DeleteModelproviderErrors];

export type DeleteModelproviderResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteModelproviderResponse =
  DeleteModelproviderResponses[keyof DeleteModelproviderResponses];

export type GetModelproviderData = {
  body?: never;
  path: {
    /**
     * Provider Id
     */
    provider_id: string;
  };
  query?: never;
  url: '/system/api/v1/modelproviders/{provider_id}';
};

export type GetModelproviderErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetModelproviderError = GetModelproviderErrors[keyof GetModelproviderErrors];

export type GetModelproviderResponses = {
  /**
   * Successful Response
   */
  200: ModelProviderResponse;
};

export type GetModelproviderResponse = GetModelproviderResponses[keyof GetModelproviderResponses];

export type GetMcpendpointsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/system/api/v1/mcpendpoints';
};

export type GetMcpendpointsErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type GetMcpendpointsResponses = {
  /**
   * Response Get Mcpendpoints
   * Successful Response
   */
  200: Array<McpEndpointResponse>;
};

export type GetMcpendpointsResponse = GetMcpendpointsResponses[keyof GetMcpendpointsResponses];

export type CreateMcpendpointData = {
  body: McpEndpointCreate;
  path?: never;
  query?: never;
  url: '/system/api/v1/mcpendpoints';
};

export type CreateMcpendpointErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateMcpendpointError = CreateMcpendpointErrors[keyof CreateMcpendpointErrors];

export type CreateMcpendpointResponses = {
  /**
   * Successful Response
   */
  201: McpEndpointResponse;
};

export type CreateMcpendpointResponse =
  CreateMcpendpointResponses[keyof CreateMcpendpointResponses];

export type DeleteMcpendpointData = {
  body?: never;
  path: {
    /**
     * Mcpendpoint Id
     */
    mcpendpoint_id: string;
  };
  query?: never;
  url: '/system/api/v1/mcpendpoints/{mcpendpoint_id}';
};

export type DeleteMcpendpointErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteMcpendpointError = DeleteMcpendpointErrors[keyof DeleteMcpendpointErrors];

export type DeleteMcpendpointResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteMcpendpointResponse =
  DeleteMcpendpointResponses[keyof DeleteMcpendpointResponses];

export type GetMcpendpointData = {
  body?: never;
  path: {
    /**
     * Mcpendpoint Id
     */
    mcpendpoint_id: string;
  };
  query?: never;
  url: '/system/api/v1/mcpendpoints/{mcpendpoint_id}';
};

export type GetMcpendpointErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetMcpendpointError = GetMcpendpointErrors[keyof GetMcpendpointErrors];

export type GetMcpendpointResponses = {
  /**
   * Successful Response
   */
  200: McpEndpointResponse;
};

export type GetMcpendpointResponse = GetMcpendpointResponses[keyof GetMcpendpointResponses];

export type UpdateMcpendpointData = {
  body: McpEndpointUpdate;
  path: {
    /**
     * Mcpendpoint Id
     */
    mcpendpoint_id: string;
  };
  query?: never;
  url: '/system/api/v1/mcpendpoints/{mcpendpoint_id}';
};

export type UpdateMcpendpointErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateMcpendpointError = UpdateMcpendpointErrors[keyof UpdateMcpendpointErrors];

export type UpdateMcpendpointResponses = {
  /**
   * Successful Response
   */
  200: McpEndpointResponse;
};

export type UpdateMcpendpointResponse =
  UpdateMcpendpointResponses[keyof UpdateMcpendpointResponses];

export type GetModelsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/system/api/v1/models';
};

export type GetModelsErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type GetModelsResponses = {
  /**
   * Response Get Models
   * Successful Response
   */
  200: Array<ModelResponse>;
};

export type GetModelsResponse = GetModelsResponses[keyof GetModelsResponses];

export type CreateModelData = {
  body: ModelCreate;
  path?: never;
  query?: never;
  url: '/system/api/v1/models';
};

export type CreateModelErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateModelError = CreateModelErrors[keyof CreateModelErrors];

export type CreateModelResponses = {
  /**
   * Successful Response
   */
  201: ModelResponse;
};

export type CreateModelResponse = CreateModelResponses[keyof CreateModelResponses];

export type DeleteModelData = {
  body?: never;
  path: {
    /**
     * Model Name
     */
    model_name: string;
  };
  query?: never;
  url: '/system/api/v1/models/{model_name}';
};

export type DeleteModelErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteModelError = DeleteModelErrors[keyof DeleteModelErrors];

export type DeleteModelResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteModelResponse = DeleteModelResponses[keyof DeleteModelResponses];

export type GetModelData = {
  body?: never;
  path: {
    /**
     * Model Name
     */
    model_name: string;
  };
  query?: never;
  url: '/system/api/v1/models/{model_name}';
};

export type GetModelErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetModelError = GetModelErrors[keyof GetModelErrors];

export type GetModelResponses = {
  /**
   * Successful Response
   */
  200: ModelResponse;
};

export type GetModelResponse = GetModelResponses[keyof GetModelResponses];

export type ListPromptsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Active
     */
    active?: boolean | null;
  };
  url: '/system/api/v1/prompts';
};

export type ListPromptsErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListPromptsError = ListPromptsErrors[keyof ListPromptsErrors];

export type ListPromptsResponses = {
  /**
   * Response List Prompts
   * Successful Response
   */
  200: Array<PromptResponse>;
};

export type ListPromptsResponse = ListPromptsResponses[keyof ListPromptsResponses];

export type CreatePromptData = {
  body: PromptCreate;
  path?: never;
  query?: never;
  url: '/system/api/v1/prompts';
};

export type CreatePromptErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreatePromptError = CreatePromptErrors[keyof CreatePromptErrors];

export type CreatePromptResponses = {
  /**
   * Successful Response
   */
  200: PromptResponse;
};

export type CreatePromptResponse = CreatePromptResponses[keyof CreatePromptResponses];

export type GetSystemDefaultPromptData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/system/api/v1/prompts/system-default';
};

export type GetSystemDefaultPromptErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type GetSystemDefaultPromptResponses = {
  /**
   * Successful Response
   */
  200: PromptResponse;
};

export type GetSystemDefaultPromptResponse =
  GetSystemDefaultPromptResponses[keyof GetSystemDefaultPromptResponses];

export type DeletePromptData = {
  body?: never;
  path: {
    /**
     * Prompt Name
     */
    prompt_name: string;
  };
  query?: never;
  url: '/system/api/v1/prompts/{prompt_name}';
};

export type DeletePromptErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeletePromptError = DeletePromptErrors[keyof DeletePromptErrors];

export type DeletePromptResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetPromptData = {
  body?: never;
  path: {
    /**
     * Prompt Name
     */
    prompt_name: string;
  };
  query?: never;
  url: '/system/api/v1/prompts/{prompt_name}';
};

export type GetPromptErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetPromptError = GetPromptErrors[keyof GetPromptErrors];

export type GetPromptResponses = {
  /**
   * Successful Response
   */
  200: PromptResponse;
};

export type GetPromptResponse = GetPromptResponses[keyof GetPromptResponses];

export type UpdatePromptData = {
  body: PromptUpdate;
  path: {
    /**
     * Prompt Name
     */
    prompt_name: string;
  };
  query?: never;
  url: '/system/api/v1/prompts/{prompt_name}';
};

export type UpdatePromptErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdatePromptError = UpdatePromptErrors[keyof UpdatePromptErrors];

export type UpdatePromptResponses = {
  /**
   * Successful Response
   */
  200: PromptResponse;
};

export type UpdatePromptResponse = UpdatePromptResponses[keyof UpdatePromptResponses];

export type ListOauthServicesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Active Only
     * Only return active services
     */
    active_only?: boolean;
  };
  url: '/api/v1/oauth/services';
};

export type ListOauthServicesErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListOauthServicesError = ListOauthServicesErrors[keyof ListOauthServicesErrors];

export type ListOauthServicesResponses = {
  /**
   * Successful Response
   */
  200: OAuthServiceListResponse;
};

export type ListOauthServicesResponse =
  ListOauthServicesResponses[keyof ListOauthServicesResponses];

export type CreateOauthServiceData = {
  body: OAuthServiceCreate;
  path?: never;
  query?: never;
  url: '/api/v1/oauth/services';
};

export type CreateOauthServiceErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateOauthServiceError = CreateOauthServiceErrors[keyof CreateOauthServiceErrors];

export type CreateOauthServiceResponses = {
  /**
   * Successful Response
   */
  201: OAuthServiceResponse;
};

export type CreateOauthServiceResponse =
  CreateOauthServiceResponses[keyof CreateOauthServiceResponses];

export type DeleteOauthServiceData = {
  body?: never;
  path: {
    /**
     * Service Id
     */
    service_id: string;
  };
  query?: never;
  url: '/api/v1/oauth/services/{service_id}';
};

export type DeleteOauthServiceErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteOauthServiceError = DeleteOauthServiceErrors[keyof DeleteOauthServiceErrors];

export type DeleteOauthServiceResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteOauthServiceResponse =
  DeleteOauthServiceResponses[keyof DeleteOauthServiceResponses];

export type GetOauthServiceData = {
  body?: never;
  path: {
    /**
     * Service Id
     */
    service_id: string;
  };
  query?: never;
  url: '/api/v1/oauth/services/{service_id}';
};

export type GetOauthServiceErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetOauthServiceError = GetOauthServiceErrors[keyof GetOauthServiceErrors];

export type GetOauthServiceResponses = {
  /**
   * Successful Response
   */
  200: OAuthServiceResponse;
};

export type GetOauthServiceResponse = GetOauthServiceResponses[keyof GetOauthServiceResponses];

export type UpdateOauthServiceData = {
  body: OAuthServiceUpdate;
  path: {
    /**
     * Service Id
     */
    service_id: string;
  };
  query?: never;
  url: '/api/v1/oauth/services/{service_id}';
};

export type UpdateOauthServiceErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateOauthServiceError = UpdateOauthServiceErrors[keyof UpdateOauthServiceErrors];

export type UpdateOauthServiceResponses = {
  /**
   * Successful Response
   */
  200: OAuthServiceResponse;
};

export type UpdateOauthServiceResponse =
  UpdateOauthServiceResponses[keyof UpdateOauthServiceResponses];

export type GetOauthAuthorizationUrlData = {
  body: OAuthAuthorizationRequest;
  path?: never;
  query?: never;
  url: '/api/v1/oauth/authorize';
};

export type GetOauthAuthorizationUrlErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetOauthAuthorizationUrlError =
  GetOauthAuthorizationUrlErrors[keyof GetOauthAuthorizationUrlErrors];

export type GetOauthAuthorizationUrlResponses = {
  /**
   * Successful Response
   */
  200: OAuthAuthorizationResponse;
};

export type GetOauthAuthorizationUrlResponse =
  GetOauthAuthorizationUrlResponses[keyof GetOauthAuthorizationUrlResponses];

export type ExchangeOauthTokenData = {
  body: OAuthTokenExchange;
  path?: never;
  query?: never;
  url: '/api/v1/oauth/token';
};

export type ExchangeOauthTokenErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ExchangeOauthTokenError = ExchangeOauthTokenErrors[keyof ExchangeOauthTokenErrors];

export type ExchangeOauthTokenResponses = {
  /**
   * Successful Response
   */
  200: OAuthTokenResponse;
};

export type ExchangeOauthTokenResponse =
  ExchangeOauthTokenResponses[keyof ExchangeOauthTokenResponses];

export type ListOauthTokensData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/oauth/tokens';
};

export type ListOauthTokensErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type ListOauthTokensResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RevokeOauthTokenData = {
  body?: never;
  path: {
    /**
     * Service Name
     */
    service_name: string;
  };
  query?: never;
  url: '/api/v1/oauth/tokens/{service_name}';
};

export type RevokeOauthTokenErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RevokeOauthTokenError = RevokeOauthTokenErrors[keyof RevokeOauthTokenErrors];

export type RevokeOauthTokenResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type RevokeOauthTokenResponse = RevokeOauthTokenResponses[keyof RevokeOauthTokenResponses];

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};
